skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_escrow = "3EU7PYuMjmJSAQHSS6LFB3F1akxk3nzu7jHPb4UAYF2t"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
